### PR TITLE
Fixed issue where non-serializable types would get into payload

### PR DESCRIPTION
**Pull request by bsneed**
Fixes issue #936 

- NSCoding conformance check was too broad.  Reduced to explicitly allowed types per Apple documentation.
- Added tests to validate non-serializable types trigger asserts in debug mode.
- Added method to do actual type validation.

### CODE REVIEW

**Comment by rogerluan** [comment]
Does this PR fix https://github.com/segmentio/analytics-ios/issues/929?

**Comment by bsneed** [comment]
@rogerluan it might, but given lack of repro steps on #929 I can't say for sure.

**Comment by tibr** [comment]
@bsneed this change removed the ability to serialize `NSURL` objects. I guess that wasn't on purpose given that it killed the [tracking of deep links](https://segment.com/docs/connections/spec/mobile/#application-opened)?

**Comment by bsneed** [comment]
@tibr I'm perplexed as to how this was working before tbh.  NSURL isn't a supported type w/ NSJSONSerializer.  A quick test confirms this.  I'll open an issue for this internally.

**Comment by tibr** [comment]
@bsneed true, but it does conform to `NSCoding` so it wasn't removed from the dictionary in `serializableDeepCopy` and then fixed in [`SEGCoerceJSONObject`](https://github.com/segmentio/analytics-ios/blob/594d0499f12a13db1eab3832030e27ff17f0dff8/Analytics/Internal/SEGUtils.m#L553).

**Comment by bsneed** [comment]
@tibr ah, good find!  I should have a fix pushed to master shortly.  Might be a bit before a release though.

**Comment by bsneed** [comment]
@tibr fix is up on master! :highfive:

**Pull request merged**
