### PR TITLE
should be OS X compatible

### PR DESCRIPTION
**Pull request by marsepu**

### CODE REVIEW

**Comment by f2prateek** [comment]
Sorry for the delay - this is a big change but this is definitely on my list to take a look at and test!

**Comment by marsepu** [comment]
Groovy. In hindsight, I should not have committed the 'Pods' in the new example directory.

**Comment by marsepu** [comment]
@f2prateek have you had a chance to test this yet?

**Comment by f2prateek** [comment]
@marsepu Sorry I've still been busy!

**Comment by f2prateek** [comment]
@marsepu this is still on the radar to be added to the library. We've been making some changes on `dev` that will make it easy to incorporate these changes rather than have macros throughout the codebase. Thanks for the contribution, and hopefully we'll get it added soon!

**Comment by f2prateek** [comment]
cc @tonyxiao

**Pull request closed without merging**
