### PR TITLE
Always deliver events asynchronously to integrations.

### PR DESCRIPTION
**Pull request by f2prateek**
Removes the ability for certain events to be delivered synchronously to integrations. 

It would be good to do a audit of integrations which need this functionality and make the fix I suggested for those integrations.

Closes #714.

### CODE REVIEW

**Comment by tonyxiao** [comment]
Btw beware of whitespace changes, they can make PR harder to review.

**Comment by tonyxiao** [comment]
@f2prateek i thought in https://github.com/segmentio/analytics-ios/pull/714 you mentioned that "certain integrations require the application state notifications hooks to be called from main thread"? In this PR we removed the ability to do synchronous delivery IN ADDITION to removing the application state notification calls from main thread. Can we confirm this won't cause issue with bundled integrations?

**Comment by f2prateek** [comment]
Yes that's right. This will cause an issue with integrations, I know for sure we'll need to update the Appboy integration. That's why I suggested the fix in the comments. I'm definitely open to other fixes, and it would be ideal to have a fix that allows for both (but #714 doesn't fix the issue).

**Comment by tonyxiao** [comment]
What if we simply got rid of queue / lock based synchronization for app state notifications?

**Comment by tonyxiao** [comment]
there doesn't seem to be any race conditions which would cause a problem in this particular case. So we can just call integration methods synchronously from the main thread where notifications originate. Without `@sychronized(self)` block things won't block.

**Comment by f2prateek** [comment]
> So we can just call integration methods synchronously from the main thread

Since sometimes integrations haven't been initialized yet, we can't always do that, and still will have to deliver them async. Hence we had the `@ sychronized(self)` block so that when that happens, the main thread and the background thread don't both deliver the event at the same time.

**Pull request merged**
