### PR TITLE
Updated MoEngage to 1.6

### PR DESCRIPTION
**Pull request by gautamMoEngage**

### CODE REVIEW

**Comment by gautamMoEngage** [comment]
@f2prateek - The error is - "All integration headers need to be made public". The thing is, that all of them are public already. You can check them. I've also sent screenshots to @francisco

**Comment by f2prateek** [comment]
How did you make the headers public?

**Comment by f2prateek** [comment]
Just FYI in case we miss each other again, you need to manually make those headers public through Xcode in our SDK. Let me know when you've done that, and we can merge this.

**Comment by gautamjain987** [comment]
@f2prateek - I was able to run local test successfully. I added the missing header manually. Circle ci failed a test case with error - SEGAnalyticsTests
  testForwardsTrackEventsInPlan, failed: caught "OCMockTestFailure", "OCPartialMockObject(SEGSegmentioIntegration): 2 expected methods were not invoked: 
  /Users/distiller/analytics-ios/AnalyticsTests/AnalyticsTests.m:222

**Comment by f2prateek** [comment]
@gautamjain987 cool!, I'll run this locally and very the build, our CI is a bit flaky unfortunately.

**Comment by f2prateek** [comment]
@gautamjain987 btw the reason I haven't merged this yet is because we're migrating the integrations into their own repos. You'll see that none of the integrations are in this repo anymore. The process will take a couple of weeks, and I'll let you know when it's done. I'll pull in these changes to the MoEngage repo manually.

**Comment by gautamMoEngage** [comment]
@f2prateek - Any updates on this. A client is waiting to get this merged. Please let me know the timeline on this.

**Comment by f2prateek** [comment]
@gautamjain987 As I said, the migration will take a couple of weeks

**Pull request closed without merging**
