### PR TITLE
Add tvOS for deployment target

### PR DESCRIPTION
**Pull request by BProg**
issue: #625

This adds possibility to build the framework for apple tv using `carthage update --platform tvOS analytics-ios`

### CODE REVIEW

**Comment by BProg** [comment]
Hi there. Any comments on this? I could rebase it and drop commit 1 and 2 but I am waiting for feedback first.

**Comment by f2prateek** [comment]
I can't find any docs on this on Carthage - could you point us to where this approach is documented?

In case there are no docs about this,  have you had a chance to test this locally? If so, we can do a manual test ourselves as well to verify.

cc @tonyxiao

**Comment by BProg** [comment]
Carthage only needs the framework to be shared. This is the only condition. 
Here I changed the Analytics framework to be cross-platform, so it can be build for apple tv and ios without need of another target for apple TV.

**Comment by BProg** [comment]
Yes I tested and it works.

**Comment by BProg** [comment]
@f2prateek - I saw circle ci is using xcode 7.0.1 for testing, but that xcode does even have a target for apple tv. Do you use xcode 7.0.1 in development? If yes, why?

**Comment by f2prateek** [comment]
I used 8.1 on my computer, probably just haven't gotten around to updating it in circle.

**Comment by BProg** [comment]
If the command `carthage build --no-skip-current` will be run in the project root folder, the folder  `Carthage/Build/` will contain now 2 folders : `iOS` and `tvOS`.

**Comment by tonyxiao** [comment]
lgtm

**Pull request merged**
