### PR TITLE
TvOS support

### PR DESCRIPTION
**Pull request by dbachrach**
Use TARGET_OS_TV to remove non-TvOS functionality.

### CODE REVIEW

**Comment by f2prateek** [comment]
@dbachrach have you been able to test this out on a tvOS device btw?

**Comment by dbachrach** [comment]
No we didn't get lucky :disappointed: This is just on the simulator. Note, I also only did this for `Analytics/Segmentio`, and not all the other integrations.

**Comment by f2prateek** [comment]
@dbachrach Thanks, yeah we don't have to worry about other integrations, since you can just do `pod Analytics/Segmentio` to use only use Segment.

**Comment by orta** [comment]
I can confirm this works on an appleTV. I had to make podspec changes though; https://github.com/orta/analytics-ios/commit/7008b17f60735444538799d1b3fac893f7eedb0d

**Comment by orta** [comment]
I intend in ARAnalytics to audit for tvOS support over time, for now I only added what I know works: https://github.com/orta/ARAnalytics/commit/1332c436ebc78e8bef5f3f8aa8d40c5ac985e963 - you may have to do the same if you're including static binaries

**Comment by JasonGallagher** [comment]
The podfile probably needs to be updated to explicitly support tvOS too, right?

**Comment by orta** [comment]
In this PR, yeah.

**Comment by f2prateek** [comment]
Updated in #509, but not complete yet :(

**Pull request closed without merging**
