### PR TITLE
1-line change that fixes a warning in Xcode

### PR DESCRIPTION
**Pull request by kelvinlauKL**
**What does this PR do?**
Modifies one line of code to remove a warning from Xcode.

**Where should the reviewer start?**
From the top. There's only one line that changed (added 8 characters).

**How should this be manually tested?**
This change is purely syntactical and functionality will not be impacted.

**Questions:**
- Does the docs need an update? - NO -
- Are there any security concerns? - NO -
- Do we need to update engineering / success? - NO -

### CODE REVIEW

**Comment by f2prateek** [comment]
What is the warning that this fixes?

**Comment by kelvinlauKL** [comment]
Screen Shot 2019-04-10 at 3 24 28 PM

**Comment by kelvinlauKL** [comment]
> What is the warning that this fixes?

Screen Shot 2019-04-10 at 3 24 28 PM

**Comment by f2prateek** [comment]
cool, LGTM! cc @fathyb

**Pull request merged**
