### PR TITLE
CLANG_WARN_STRICT_PROTOTYPES: Yes please!

### PR DESCRIPTION
**Pull request by DwayneCoussement**
**What does this PR do?**
It enables strict-prototype, which is better.

**Where should the reviewer start?**
The PR is deadsimple, so just read the PR.

**How should this be manually tested?**
Check if the UUID is still generated, check if the gzip still works

**Any background context you want to provide?**
Xcode 9 enforces this flag and cocoapods doesn't inhibit those warnings yet.

**What are the relevant tickets?**
N/A

**Screenshots or screencasts (if UI/UX change)**
N/A

**Questions:**
- Does the docs need an update? No
- Are there any security concerns? No
- Do we need to update engineering / success? No

@segmentio/gateway

### CODE REVIEW

**Comment by DwayneCoussement** [comment]
@tonyxiao could you have a look into this, pls? 😁 it's a very minor PR...

**Comment by Fengson** [comment]
What is the status on this? When can we expect to see this released? Thanks!

**Comment by f2prateek** [comment]
Believe this is already released on the latest version. Are you seeing otherwise?

**Comment by Fengson** [comment]
I must have been using older version. Thanks for clarification, @f2prateek 👍

**Pull request merged**
