### PR TITLE
Add UXCam integration

### PR DESCRIPTION
**Pull request by f2prateek**

### CODE REVIEW

**Comment by f2prateek** [comment]
@richardgroves did you do anything special to build the project? I'm running into this error - https://cloudup.com/cKdKe6RJVNN - when I execute `make build`.

**Comment by richardgroves** [comment]
Hi,

No I didn't need anything special. That is a rather cryptic error message it is giving you...

Could you make any other changes to the master repo and I can try and re-do the UXCam integration and make a new PR to see if that cures any problem.

As far I can tell I didn't do anything special - your integration setup is all nicely done to make it easy to add in to.

**Comment by f2prateek** [comment]
@richardgroves Turns out I forgot to import a header lol, you'd think the error message was a bit nicer. We're running into another issue with the `load` method on the UXCam integration not being called, but that's an issue on our side.

**Comment by richardgroves** [comment]
Is there anything I can do to help around the 'load' method issue?

**Comment by f2prateek** [comment]
@richardgroves could you try making the re-adding the integration from `master`? I've tried a couple of different force the load method to be called, but nothing has worked.

**Comment by richardgroves** [comment]
having problems - your 'master' branch wont compile for me as Countly have changed their version numbering (nice....) and the referenced 3.0.0 no longer exists (seems it is now 15.06).

Will hack around a bit, but don't want to go causing more merge conflicts.

screen shot 2015-07-06 at 18 20 42

**Comment by richardgroves** [comment]
Joy - they still have 3.0.0 published on Cocoapods, but no github/zip to back it up. Will file an issue with them.

**Comment by richardgroves** [comment]
By recreating everything I think I found the problem - the SEGUXCamIntegration.m file wasn't included in the build for the Test project when I re-did it. That meant that the 'build' target worked, but the 'test' went wrong as it never loaded the UXCam integration. 

Have done it all over and will send another pull request relative to the current master.

**Comment by f2prateek** [comment]
@richardgroves awesome, thanks for your work!

**Pull request closed without merging**
