### PR TITLE
SEGGoogleAnalyticsIntegration: Replace usage of Google Analytics defaultTracker with instance property.

### PR DESCRIPTION
**Pull request by johnhaitas**
SEGGoogleAnalyticsIntegration uses [[GAI sharedInstance] defaultTracker]. This is a problem if a tracker has been initialized before SEGGoogleAnalyticsIntegration's -start method is called. This can be resolved by SEGGoogleAnalyticsIntegration maintaining its own tracker instance property and using that instead of [[GAI sharedInstance] defaultTracker].

### CODE REVIEW

**Comment by johnhaitas** [comment]
this is to address this issue https://github.com/segmentio/analytics-ios/issues/271

**Comment by f2prateek** [comment]
What happens if our users do want to call some method not supported by us on the tracker?

**Comment by johnhaitas** [comment]
That `tracker` property could be made public if necessary or accessed in a different way.

What if your users want to use multiple trackers? (we are)

**Comment by f2prateek** [comment]
I think using multiple trackers is likely a smaller use case than using a single one tracker

I'm not saying we should't support this feature, we just have to think about it a bit.

**Comment by sperand-io** [comment]
closing in favor of #276. thanks!

**Pull request closed without merging**
