### PR TITLE
Release 3.5.3

### PR DESCRIPTION
**Pull request by tonyxiao**
* Make referrer access thread safe
* End background task as soon as flushing is complete
* Redispatch callback from SEGHTTPClient for thread safety
* Update cdn hostname from cdn.segment.com to cdn-settings.segment.com

### CODE REVIEW

**Comment by tonyxiao** [comment]
As usual, please ignore circle build status because we are not using circle on master branch yet (Only on dev, merge coming)

**Comment by tonyxiao** [comment]
@ladanazita @f2prateek @rbranson FYI. 

Would appreciate a LGTM

**Comment by tonyxiao** [comment]
@rbranson let us know when you are able to confirm.

**Comment by brianmichel** [comment]
Hey folks, did this happen? There's a 3.5.3 available by way of CocoaPods but I don't see the referrer retain fix when using that version of the library.

**Comment by tonyxiao** [comment]
hey @brianmichel we decided to ship a super targetted bug fix for 3.5.3 instead. The referrer retain fix will be part of the next version.

**Comment by f2prateek** [comment]
LGTM, need to update it to 3.5.4

**Pull request closed without merging**
