### PR TITLE
Update to Crittercism 5.2.0

### PR DESCRIPTION
**Pull request by joemasilotti**
Two nights ago iTunes Connect started requiring that all .sh files bundled with an app must be code signed. The Crittercism SDK includes a .sh file to automatically upload dSYMs. This update, 5.2.0, removes the script from the `resources` part of the Podspec so it will not get bundled with the app.

Before this is merged any app using the `Analytics/Crittercism` pod will not be able to push builds to iTunes Connect and TestFlight.

### CODE REVIEW

**Comment by sperand-io** [comment]
Thanks @joemasilotti! We'll be reviewing shortly.

**Comment by f2prateek** [comment]
@joemasilotti Are you able to build the library? The update fails the build with this message https://cloudup.com/cuNNErl9Q4u

**Comment by joemasilotti** [comment]
I am not able to build the library either. Interestingly enough I can't build master on my machine, either. Are there any dependency or prereq steps required to build the library other than the Cocoapod dependencies?

**Comment by f2prateek** [comment]
Interesting, I know we've had some issues with builds, I can build master locally but not on our CI. What version of CocoaPods and Xcode/xcodebuild are you using?

**Comment by joemasilotti** [comment]
I'm using Xcode 6.3 and tried with both Cocoapods 0.35.0 and 0.36.3.

**Comment by bhlvoong** [comment]
Getting multiple errors lately on both work and home machines. I was able to build using this commit has by including this line in my Podfile:
pod 'Analytics', :git => 'git@github.com:joemasilotti/analytics-ios.git', :commit => '41cf313b334b9886f634e8d71d2b65bcfab84a8a'

and then running 
sudo gem install cocoapods
rm -rf ~/.cocoapods
pod setup
rm -rf $ios_project/Pods
pod install

**Comment by platedbay** [comment]
We would love for this to make it in, so please let me know if there's any way I can help out.

**Comment by f2prateek** [comment]
https://github.com/segmentio/analytics-ios/pull/315

**Pull request closed without merging**
