### PR TITLE
Fix Xcode 9 "This function declaration is not a prototype" warnings

### PR DESCRIPTION
**Pull request by TylerTheCompiler**
**What does this PR do?**
Fixes warnings in Xcode 9 when using this library as a Cocoapod. The warnings are "This function declaration is not a prototype" and are caused by not putting `void` in empty function/block prototypes and having CLANG_WARN_STRICT_PROTOTYPES turned on (which Xcode 9 turns on when you update projects to recommended settings).

**Where should the reviewer start?**
At the beginning?

**How should this be manually tested?**
Try building the Analytics framework target on Xcode 9 after having turned on CLANG_WARN_STRICT_PROTOTYPES.

**What are the relevant tickets?**
Not sure.

**Questions:**
- Does the docs need an update?
No

- Are there any security concerns?
No

@segmentio/gateway

### CODE REVIEW

**Comment by f2prateek** [comment]
Closed by #709

**Comment by f2prateek** [comment]
Thanks for the PR btw! Sorry for the work

**Comment by TylerTheCompiler** [comment]
No prob! And no worries, I somehow missed #709 existing. Thanks for merging that in!

**Comment by chrismanderson** [comment]
Any news on when we'll get a version cut with this in there? Would love to remove these Xcode warnings.

**Comment by Fengson** [comment]
It's been over 2 months since last post.
Can anyone update us on a progress regarding releasing this to public?

**Comment by TylerTheCompiler** [comment]
@Fengson Looks like this was already released in 3.6.9 about 15 days ago. I guess 3.6.8 was skipped.

**Comment by Fengson** [comment]
Thanks for the info @TylerTheCompiler !

**Pull request closed without merging**
