### PR TITLE
Screen tracking doesn't always produce desired name. Fix for issue #654

### PR DESCRIPTION
**Pull request by bfernandesbfs**
I added some conditions that are able to get the tracking of the screen automatically!

### CODE REVIEW

**Comment by f2prateek** [comment]
LGTM, cc @tonyxiao

**Comment by tonyxiao** [comment]
Is it worth adding test coverage for this @f2prateek ?

**Comment by f2prateek** [comment]
@bfernandesbfs can you reopen this against the `dev` branch? Tests would also be welcome if you can.

**Comment by tonyxiao** [comment]
@f2prateek we can actually change the base branch ourselves :)

**Comment by tonyxiao** [comment]
Strange that it's not triggering a circle rebuild after changing base branch.

**Comment by bfernandesbfs** [comment]
Ok!  I will send to dev branch and I try test too

**Pull request closed without merging**
