### PR TITLE
Sprint 11

### PR DESCRIPTION
**Pull request by f2prateek**

### CODE REVIEW

**Comment by imajes** [comment]
hey, just curious, is there a reason you rolled (rebased) these commits up and force-pushed?

**Comment by f2prateek** [comment]
@imajes it was a mistake, these are on master now and will be in the next release.

**Comment by imajes** [comment]
@f2prateek: how do you mean? these commits got removed from the repo it seems.

**Comment by f2prateek** [comment]
Oh I see, yes, they were squashed into a single commit (I had accidentally clicked the squash and rebase button instead of merge) https://github.com/segmentio/analytics-ios/commit/581cf3f4316fad57f477a9ac4e8bffffd1f0b1b3. 

The changes are still available on master though.

**Pull request merged**
