### PR TITLE
Bumped pod to 1.8.

### PR DESCRIPTION
**Pull request by gautamMoEngage**
Enabled modules.
Changed header path for MoEngage to match the pod settings.
Expecta, OCMock and OCHamcrest automatically updated via pod update.

### CODE REVIEW

**Comment by gautamMoEngage** [comment]
@f2prateek - I'm getting the error "these headers need to be made public". Also, headers which are in Pods are not copied in the Segment folder. I see that pull requests (Apptimize, Amplitude, Taplytics) are also facing issues, while all they are trying to do it update the pod, same as me. I might be wrong, but can you look at it once if there might be an issue on your end.

**Comment by f2prateek** [comment]
I was able to update all the other integrations, but not MoEngage https://cloudup.com/cOK5gUA7bKQ

**Comment by gautamMoEngage** [comment]
Strange. I will have a look at it. I don't know why it's showing duplicate symbols.

**Comment by gautamMoEngage** [comment]
Ok. So I found what is the issue. You are not supporting Bitcode, and you are probably using Xcode 6.x. My SDK is bitcode enabled and is built with Xcode 7. https://forums.developer.apple.com/thread/17529.

One of my clients needs Bitcode support. Can you try with Xcode 7 and building your SDK with bitcode enabled? If not, when do you plan to support bitcode?

**Comment by francisco** [comment]
Hey @gautamMoEngage -

We don't yet have a specific timeline for supporting Bitcode. 

Would it be possible to resubmit the PR with your 1.7 release which according to our mutual client works if we don't support bitcode? Assuming doing so would also resolve the client's issue.

Francisco

**Pull request closed without merging**
