### PR TITLE
Swift cocoapods fix

### PR DESCRIPTION
**Pull request by tonyxiao**
Needed to make these changes to make Analytics work in a swift project that uses cocoapods.

### CODE REVIEW

**Comment by tonyxiao** [comment]
Ooops, just noticed a lot of whitespace changes. Sorry annoying editor.

**Comment by f2prateek** [comment]
@tonyxiao Thanks for this, wouldn't we need to update the cocoapods version being used since swift support was only added 0.36.0 - or is that only for those who're directly using swift code in their project?

**Comment by tonyxiao** [comment]
user who want to use this with swift will need to use cocoapods 0.36.0 or higher yes.

**Comment by f2prateek** [comment]
Thanks!

**Pull request merged**
