### PR TITLE
Extract UIApplication to permit linkage with iOS extensions.

### PR DESCRIPTION
**Pull request by benshan**
**What does this PR do?**
Extract usage of UIApplication into protocol and optional property on config, so the sdk can be used with iOS extensions.

**Where should the reviewer start?**
SEGAnalyticsConfiguration.h

**How should this be manually tested?**
Link with an iOS app, set breakpoints in the appropriate UIApplication notification handlers.

**Any background context you want to provide?**
Also set APPLICATION_EXTENSION_API_ONLY=YES to guard this at build time.

**What are the relevant tickets?**
#213 

**Screenshots or screencasts (if UI/UX change)**
NA

**Questions:**
- Does the docs need an update?
Yes, now by default the optional config.application will be nil unless a non-extension target sets it to UIApplication.shared.

- Are there any security concerns?
No

- Do we need to update engineering / success?
Not sure. Would be nice to build out TestApplication more and add a test to fire UIApplicationDidEnterBackground, and assert that a bg task is added, then removed when the handler is called.

@segmentio/gateway

### CODE REVIEW

**Comment by tonyxiao** [comment]
This is a super comprehensive PR. Thank you very much for this. My only question would be what happens when the library is used from an iOS application? Wouldn't user now need to explicitly set `[UIApplication sharedApplication]` to `SEGAnalyticsConfiguration` otherwise library will behave in backward incompatible ways? Can we configure it automatically based on whether or not `UIApplication` is available at runtime?

**Comment by benshan** [comment]
@tonyxiao, yes, that was my main concern as well. The best I can come up with for runtime config is to use objc runtime to try to get sharedApplication via string name. That should appease the compiler while still getting the benefits of the build setting to warn of regression. (even better if all the warnings are cleaned and then enable treat warnings as errors)  We should probably test this approach both in an app target and in an extension to see if it works properly.

**Comment by benshan** [comment]
@tonyxiao see last commit that I pushed. This is what I'm thinking. It seems to work in my testing, and it doesn't interfere with APPLICATION_EXTENSION_API_ONLY = YES.

**Comment by benshan** [comment]
If you think a code comment is necessary in that new block to explain why it's done that way, let me know.

**Comment by benshan** [comment]
Also note that you could use the technique in the last commit with the original code, without extraction of UIApplication protocol and optional injection. I think the DI is nicer because we can now unit test these flows, but it's really up to your team wrt what you prefer.

**Comment by tonyxiao** [comment]
This is awesome! Thank you for the thoughtfulness and fine attention here. Merging.

**Comment by pixelmatrix** [comment]
FYI this PR is causing some issues in our Swift application. We use background tasks for various operations, and after upgrading to this version the compiler complains about `UIApplication.shared.endBackgroundTask(_)` with a UIBackgroundTaskIdentifier (Int). It now wants a UInt instead. It's easy enough to convert, but feels wrong to need to do that.

**Comment by benshan** [comment]
@pixelmatrix what is your SDKROOT? At least with iOS10, Apple has these background task APIs using a type `UIBackgroundTaskIdentifier` which is `typedef NSUInteger UIBackgroundTaskIdentifier;` from UIApplication.h. So likely you would need to change this to avoid warnings in the future.

Our direct conformance cover might be making that more front and center, though I haven't seen this issue in our codebase which is a mix of objc/swift. An alternative for this PR is to change `SEGApplicationProtocol` to be a protocol which does not use the Apple types, then wrap/marshal in the conformance extension.

**Comment by benshan** [comment]
Depending on all the versions of iOS that Segment supports, perhaps the easier thing to do is add a conditional compile here for the type, then include the different variations Apple has applied over those versions. I don't have UIApplication.h handy from earlier versions, but I assume this API directly used NSInteger at one point and now has been extracted as a typedef and the underlying type changed.

**Comment by pixelmatrix** [comment]
Our SDK is set to 10.3, so it's using the most recent version. I'm seeing NSUInteger in UIApplication.h, but looking at the swift headers I see `public typealias UIBackgroundTaskIdentifier = Int`

**Comment by benshan** [comment]
@pixelmatrix I am able to repro, and I coded a decent workaround, so please don't pollute your code with the conversion. Give me a day or so to clean it up and submit here. I tested with Xcode9b3 and this is no longer an issue there, so likely was a stale manual Swift mapping in UIApplication which got out of sync.

**Comment by pixelmatrix** [comment]
Awesome, thank you for the prompt response

**Comment by benshan** [comment]
@pixelmatrix see referenced PR. Can you try applying locally and confirming that it fixes for you? (I have added an automation test as well, TDD style, which would have caught it.)

**Comment by pixelmatrix** [comment]
@benshan just applied that branch to our app and it compiled just fine. looks like it's fixed!

**Comment by benshan** [comment]
Thanks @pixelmatrix for confirming!

**Pull request merged**
